// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1oyXPGv8yrJAYwYBIbfP0L5qc1BpdS1I',
    appId: '1:610950052144:android:cfdbfcbf9b6a208ee2f0f5',
    messagingSenderId: '610950052144',
    projectId: 'orderviteapp-fa32e',
    storageBucket: 'orderviteapp-fa32e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANO4nsEcMlDbqceEuqAy9JP-gZ0OlGT34',
    appId: '1:610950052144:ios:380736e37fb91361e2f0f5',
    messagingSenderId: '610950052144',
    projectId: 'orderviteapp-fa32e',
    storageBucket: 'orderviteapp-fa32e.firebasestorage.app',
    androidClientId: '610950052144-fafjvcd7i590o9ip8b56s4njt3305foj.apps.googleusercontent.com',
    iosClientId: '610950052144-qakhqd1efamvso10soib010eung9feok.apps.googleusercontent.com',
    iosBundleId: 'com.ordervite.app',
  );
}
